stages:
#- dich
- testing
#- code check
#  - test-api

cache:
  paths:
  - build

dich:
  image: epcallan/php7-testing-phpunit:7.2-phpunit7
  stage: dich
  script:
  - composer install --ignore-platform-reqs
  - phpunit --log-junit build/index.xml --coverage-xml build/coverage --coverage-clover build/coverage/coverage_index.xml

unit-tests:
  stage: testing
  image: ${CI_REGISTRY}/nexteum-user/nexteum-user-php:7.2-fpm-alpine-dev
  cache:
#    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
    - vendor/
#  before_script:
#  - eval $(ssh-agent -s)
#  - mkdir -p ~/.ssh
#  - echo "${SSH_PRIVATE_KEY}" | ssh-add -
#  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
  # Install DEVELOPMENT dependencies
  - composer install --dev --optimize-autoloader --no-ansi --no-interaction --no-scripts
  - cp ./phpunit.xml.dist ./phpunit.xml
  - vendor/bin/phpunit --configuration ./phpunit.xml --coverage-text --colors=never ./tests
#  except:
#  - develop
#  - master


code check:
  image: emeraldsquad/sonar-scanner:latest
  stage: code check
  script: sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectVersion=$CI_BUILD_ID -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=src -Dsonar.coverage.exclusions=*.js,*.css,*.html,**Interface.php,**Kernel.php -Dsonar.php.tests.reportPath=build/index.xml -Dsonar.php.coverage.reportPaths=build/coverage/coverage_index.xml
