<?php
/**
 * Created by PhpStorm.
 * User: ivan.me
 * Date: 05.03.2019
 * Time: 15:39
 */

namespace App\Service;

use Elasticsearch\Client;
use Elasticsearch\ClientBuilder;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class ElasticSearchClientTest extends KernelTestCase
{
    /**
     * @var ElasticSearchClient
     */
    protected $elasticClient;

    /**
     * @dataProvider dataProviderGetTimePerComponent
     * @param $value
     */
    public function testGetTimePerComponent($value)
    {
        $clientBuilder = $this->createMock(ClientBuilder::class);
        $clientBuilder->expects($this->once())
                      ->method('setHosts')
                      ->willReturn($clientBuilder);

        $client = $this->createMock(Client::class);
        $returnValue['aggregations']['time']['value'] = $value;
        $client->expects($this->once())
               ->method('search')
               ->willReturn($returnValue);
        $clientBuilder->expects($this->once())
                      ->method('build')
                      ->willReturn($client);
        $client = new ElasticSearchClient($clientBuilder, 'qwe');
        $this->assertEquals($value, $client->getTimePerComponent('php', 'ivan.melnichuk'));
    }

    public function dataProviderGetTimePerComponent()
    {
        return [
            [0],
            [132.22000004723668]
        ];
    }

    protected function setUp()
    {
        self::bootKernel();
        $this->elasticClient = self::$kernel->getContainer()->get(ElasticSearchClient::class);
        parent::setUp(); // TODO: Change the autogenerated stub

    }
}
