nginx:
  restart: always
  image: registry.devzone.net/mygarage/mygarage-nginx:1-alpine
  volumes:
  - ../:/application
  - phpsocket:/var/run
  - ./site.conf:/etc/nginx/conf.d/site.conf
  environment:
    PHP_FPM_HOST: php-fpm
    PHP_FPM_PORT: 9000
  ports:
  - 8080:90
  links:
  - php-fpm
php-fpm:
  build: .
  dockerfile: Dockerfile
  restart: always
  volumes:
    - ../:/application
    - phpsocket:/var/run
  environment:
      XDEBUG_CONFIG: remote_enable=0 remote_host=10.0.5.86
      PHP_IDE_CONFIG: serverName=symfony-demo
db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: my_secret_pw_shh
    MYSQL_DATABASE: test_db
    MYSQL_USER: devuser
    MYSQL_PASSWORD: devpass
  ports:
  - "9906:3306"