nginx:
  restart: always
  image: registry.devzone.net/mygarage/mygarage-nginx:1-alpine
  volumes:
  - ../:/application
  - phpsocket:/var/run
  - ./site.conf:/etc/nginx/conf.d/site.conf
  environment:
    PHP_FPM_HOST: php-fpm-2
    PHP_FPM_PORT: 9000
  ports:
  - 8080:90
  links:
  - php-fpm-2
php-fpm-2:
  build: .
  dockerfile: Dockerfile
  restart: always
  volumes:
    - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    - ../:/application
    - phpsocket:/var/run
  environment:
    XDEBUG_CONFIG: remote_enable=1 remote_host=host.docker.internal
    PHP_IDE_CONFIG: serverName=symfony-demo
db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: my_secret_pw_shh
    MYSQL_DATABASE: test_db
    MYSQL_USER: devuser
    MYSQL_PASSWORD: devpass
  ports:
  - "9906:3306"