<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2/10/2019
 * Time: 12:17 PM
 */

namespace App\Service\PhpDeveloperTest;

use App\Entity\PhpDeveloperLevel;
use App\Entity\PhpDeveloperLevelTest;
use App\Entity\User;
use App\Entity\UserPhpDeveloperLevelRelation;
use App\Service\PhpDeveloperTest\TechnicalComponents\TechnicalComponentBuilder;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class PhpDeveloperTestsInformationBuilderTest extends KernelTestCase
{
    protected $builderMock;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->builderMock = $this->createMock(TechnicalComponentBuilder::class);
        $this->builderMock->method('build')->willReturn([]);
    }

    /**
     * @throws Exception\NoExistsNewLevelOfDeveloper
     * @throws PhpDeveloperTestBuilderException
     */
    public function testBuild()
    {
        $builder = new PhpDeveloperTestsInformationBuilder($this->builderMock);
        $user = new User();
        $phpDeveloperLevelRelation = new UserPhpDeveloperLevelRelation();
        $phpDeveloperLevel = new PhpDeveloperLevel();
        $nextLevel = new PhpDeveloperLevel();
        $phpDeveloperTest = new PhpDeveloperLevelTest();
        $phpDeveloperLevel->setNextLevel($nextLevel);
        $nextLevel->addPhpDeveloperLevelTest($phpDeveloperTest);
        $phpDeveloperLevelRelation->setPhpDeveloperLevel($phpDeveloperLevel);

        $user->setPhpDeveloperLevelRelation($phpDeveloperLevelRelation);
        $result = $builder->build($user);

        $expectedResult = [new PhpDeveloperTestInformation($phpDeveloperTest, false, [])];
        $this->assertEquals($expectedResult, $result);
    }
}
