<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2/10/2019
 * Time: 12:17 PM
 */

namespace App\Service\PhpDeveloperTest;

use App\Entity\User;
use Doctrine\ORM\EntityManager;
use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class PhpDeveloperTestsInformationBuilderTest extends KernelTestCase
{
    /**
     * @var EntityManager
     */
    protected $entityManager;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $kernel = self::bootKernel();

        $this->entityManager = $kernel->getContainer()
                                      ->get('doctrine')
                                      ->getManager();
    }

    public function testBuild()
    {
        $userRepository = $this->entityManager->getRepository(User::class);
        $user = $userRepository->findOneBy(['email' => 'junior1@onyx.com']);
        $result = PhpDeveloperTestsInformationBuilder::build($user);
        $this->assertTrue(current($result)->isPassed());
        $this->assertFalse(next($result)->isPassed());
        $this->assertFalse(next($result)->isPassed());
    }
}
