<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 2/8/2019
 * Time: 2:58 PM
 */

namespace App\Service;

use App\Entity\User;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class UserInformationServiceTest extends KernelTestCase
{

    /**
     * @var EntityManager
     */
    protected $entityManager;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $kernel = self::bootKernel();

        $this->entityManager = $kernel->getContainer()
            ->get('doctrine')
            ->getManager();
    }

    public function testGetPhpDeveloperNotPassedTests()
    {
        $userRepository = $this->entityManager->getRepository(User::class);
        $user = $userRepository->findOneBy(['email' => 'junior1@onyx.com']);
        $result = UserInformationService::getPhpDeveloperNotPassedTests($user);
        $this->assertCount(2, $result);
    }
}
